Components/CartSummaryViewComponent.cs
/*
    Will take advantage of the service created in order to receive a Cart as a cstor argument
 */
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;

namespace SportsStore.Components {
    public class CartSummaryViewComponent : ViewComponent {
        private Cart cart;
        public CartSummaryViewComponent(Cart cartService) {
            cart = cartService;
        }
        public IViewComponentResult Invoke() {
            return View(cart);
        }
    }
}

Components/NavigationMenuViewComponent.cs
// this class helps to create a system of reusable navigation control and 
// it is going to be integrated in the shared layout
// it helps creates smaller segments of an application while preserving the overall MVC approach
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using SportsStore.Models;

namespace SportsStore.Components {

    public class NavigationMenuViewComponent : ViewComponent {

        private IProductRepository repository; // helps getting the liste of product which will be category filtered
        // cstor
        public NavigationMenuViewComponent(IProductRepository repo)
        {
            repository = repo;
        }
        // the invoke methode is called when the component is used in a Razor view and the result of it is 
        // inserted into the HTML sent to the browser
        // within a view, view components are used through the @awaitComponent.InvokeAsynch expression
        // RouteData property from the ViewComponent Class helps to access the request data in order to get the value for
        // the current selected category
        public IViewComponentResult Invoke() {
            ViewBag.SelectedCategory = RouteData?.Values["category"]; // to pass the category to the view :could use a view model class for that
            return View(repository.Products
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x =>x));
        }
    }
}

Controllers/CartController.cs
using System.Linq;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SportsStore.Infrastructure;
using SportsStore.Models;
using SportsStore.Models.ViewModels;

namespace SportsStore.Controllers {
    public class CartController : Controller {
        private IProductRepository repository;
        private Cart cart;
        public CartController(IProductRepository repo, Cart cartService) {
            repository = repo;
            cart = cartService;
        }
        // index method of cart page
        public ViewResult Index(string returnUrl)
        {
            return View(new CartIndexViewModel {
                            Cart = this.cart,
                            ReturnUrl = returnUrl
                        });
        }
        // RedirectToAction method send an HTTP redirect instruction to the client browser asking browser
        // to request a new URL : In this case Index action of the cart controller.
        public RedirectToActionResult AddToCart(int productId, string returnUrl) 
        {
            // on recoit le paramètre envoyé par post du formulaire, ensuite on vérifie si le produit fait partie
            // de la base de données ou existe tout simplement, et on l'ajoute au shopping cart
            Product product = repository.Products
                .FirstOrDefault(p => p.ProductID == productId);
            if (product != null) 
            {
                cart.AddItem(product, 1);
            }
            return RedirectToAction("Index", new { returnUrl }); // return where we left off while shopping
        }
        public RedirectToActionResult RemoveFromCart(int productId, string returnUrl) 
        {
            Product product = repository.Products
                .FirstOrDefault(p => p.ProductID == productId);
            if (product != null) {
                cart.RemoveLine(product);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        // utilisation de ASP.NET session state feature
        // private Cart GetCart() 
        // {// si la session est présente et que le cart existe pas, on renvoit une nouveau cart
        // // ?? called null coalescing operator : set Session<cart> to new Cart() if Session<Cart> is undefined or not present
        //     Cart cart = HttpContext.Session.GetJson<Cart>("Cart") ?? new Cart();
        //     return cart;
        // }
        // private void SaveCart(Cart cart) 
        // {
        //     HttpContext.Session.SetJson("Cart", cart);
        // }
    }
}

Views/Shared/ProductSummary.cshtml
@model Product

<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>
            @Model.Name
            <span class="badge badge-pill badge-primary" style="float:right">
                <small>@Model.Price.ToString("c")</small>
            </span>
        </h4>
    </div>
    <form id="@Model.ProductID" asp-action="AddToCart" asp-controller="Cart" method="post">
        <input type="hidden" asp-for="ProductID" />
        <!-- @ViewContext : méthode disponible à la vue afin d'avoir access à l'état actuel de la page : ici son url !-->
        <input type="hidden" name="returnUrl"
               value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <span class="card-text p-1">
            @Model.Description
            <button type="submit"
                class="btn btn-success btn-sm pull-right" style="float:right">
                Add To Cart
            </button>
        </span>
    </form>
</div>

Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" asp-href-include="lib/bootstrap/dist/css/*.min.css" />
    <title>@ViewBag.Title</title>
    <style>
        .input-validation-error
        { 
            border-color: red; 
            background-color: #fee ; 
        }
    </style>
    <script src="/lib/jquery/dist/jquery.min.js"></script>
    <script src="/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script
      src="/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js">
    </script>
</head>
<body class="m-1 p-1">
    <div class="bg-info p-2 row">
        <div class="col">
            <h4>@ViewBag.Title</h4>
        </div>
        <div class="col-2">
            <a class="btn btn-sm btn-primary"
               asp-action="Logout" asp-controller="Account">Log Out</a>
        </div>
    </div>
    @if (TempData["message"] != null) 
    {
        <div class="alert alert-success">
            @TempData["message"]
        </div>
    }
    @RenderBody()
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet"
          asp-href-include="/lib/bootstrap/dist/**/*.min.css"
          asp-href-exclude="**/*-reboot*,**/*-grid*" />
    <link rel="stylesheet" asp-href-include="/lib/fontawesome/css/*.css" />
    <title>SportsStore</title>
</head>
<body>
    <div class="navbar navbar-inverse bg-inverse" role="navigation">
        <div class="row">
            <a class="col navbar-brand" href="#">SPORTS STORE</a>
            <div class="col-4 text-right">
                @await Component.InvokeAsync("CartSummary")
            </div>
        </div>
    </div>
    <div class="row m-1 p-1">
        <div id="categories" class="col-3">
            @await Component.InvokeAsync("NavigationMenu")
        </div>
        <div class="col-9">
            @RenderBody()
        </div>
    </div>
</body>
</html>